---
abstract: 'Like Carp::Always, but dumps the content of function arguments'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Always-Dump
requires:
  Carp::Always: 0
  Data::Dump: 0
  Data::Dump::OneLine: 0
  Monkey::Patch::Action: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Carp-Always-Dump
  homepage: https://metacpan.org/release/Carp-Always-Dump
  repository: git://github.com/sharyanto/perl-Carp-Always-Dump.git
version: 0.06
